version: 2

jobs:
  Filesize:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: npm version
      - run: npm ci
      - run: npm run bundlesize

  Lint:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: npm version
      - run: npm ci
      - run: npm run lint

workflows:
  version: 2
  Build and Test:
    jobs:
      - Filesize
      - Lint
