name: Test

on: [push, pull_request]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  # changes:
  #   name: Check for changes
  #   runs-on: ubuntu-latest
  #   outputs:
  #     src: ${{ steps.filter.outputs.src }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dorny/paths-filter@v2
  #       id: filter
  #       with:
  #         filters: |
  #           src:
  #             - 'src/**'
  #             - 'scripts/**'
  #             - 'patches/**'

  test:
    name: Test
    # if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Precheck
        run: npm run ci:precheck

      - name: Run Jest tests
        run: npm run test:ci
